nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000']
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: null


# Access to fetch at 'http://localhost:8081/login' from origin 'http://localhost:3000' has been blocked by CORS policy: 
    # Response to preflight request doesn't pass access control check: 
        # No 'Access-Control-Allow-Origin' header is present on the requested resource. 
        
    # If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

    paths:
        '^/': null
        '/*':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
            # allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

        # '^/': null
        # '^/register':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Access-Control-Allow-Origin']
        #     allow_methods: ['POST','GET']
        #     max_age: 3600
        # '^/login':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Access-Control-Allow-Origin']
        #     allow_methods: ['POST','GET']
        #     max_age: 3600
        # '^/addValueTasksWeek':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['PUT']
        #     max_age: 3600
        # '^/addTasks':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['POST']
        #     max_age: 3600
        # '^/checkFamilyKey':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['POST']
        #     max_age: 3600
        # '^/updateSubscriptionKey':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['PUT']
        #     max_age: 3600
        # '^/userDetails':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['GET']
        #     max_age: 3600
        # '^/createNewMember':
        #     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        #     allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
        #     allow_methods: ['PUT']
        #     max_age: 3600
