# Génére un fichier de configuration pour le déploiement de l'application
# sur un serveur de test
name: Deployment Test

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Install dependencies
              run: npm install
    
            - name: Build
              run: npm run build
              
            # - name: Add SSH key and known hosts
            #   run: |
            #   echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            #   chmod 600 ~/.ssh/id_rsa
            #   ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
            #   rsync -e "ssh -o StrictHostKeyChecking=no" ${{ secrets.ARGS }} ${{ secrets.SOURCE }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}

            - name: Deploy
              # uses: easingthemes/ssh-deploy@v2.1.5
              run: npm run deploy
              # with:
              #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              #   ARGS: "-rltgoDzvO"
              #   SOURCE: "dist/"
              #   REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
              #   REMOTE_USER: ${{ secrets.REMOTE_USER }}
                # TARGET: ${{ secrets.REMOTE_TARGET }}
